<?php

namespace TransactionBundle\Repository;

/**
 * CanceledSTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CanceledSTransactionRepository extends \Doctrine\ORM\EntityRepository
{
}
