<?php

namespace TransactionBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByTrackedStock()
    {
        /*$dql = "SELECT p FROM TransactionBundle:Product p JOIN p.stock Where stock.tracked = true";
        $query = $this->_em->createQuery($dql);
        return $results = $query->getResult();*/
    }
    
}
