<?php

namespace TransactionBundle\Repository;

/**
 * PTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PTransactionRepository extends \Doctrine\ORM\EntityRepository
{

}
