<?php

namespace TransactionBundle\Repository;

/**
 * SaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSaleFromTo($initDate, $finalDate, $product)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('e')
            ->from('TransactionBundle:Sale', 'e')
            ->where('e.createdAt >= :initDate')
            ->andWhere('e.createdAt <= :finalDate')
            ->andWhere('e.product = :product')
            ->setParameter('product', $product)
            ->setParameter('initDate', $initDate->format('Y-m-d'))
            ->setParameter('finalDate', $finalDate->format('Y-m-d'));

    $result = $qb->getQuery()->getResult();

    return $result;
    }
}
