<?php

namespace TransactionBundle\Repository;

/**
 * SaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFromTo(\Datetime $initDate, $finalDate, $product)
    {
        $from = new \DateTime($initDate->format("Y-m-d")." 00:00:00");
        $to   = new \DateTime($finalDate->format("Y-m-d")." 23:59:59");

        $qb = $this->createQueryBuilder("e");
        $qb->select('e')
            ->where('e.product = :product')
            ->andWhere('e.createdAt BETWEEN :from AND :to')
            ->setParameter('product', $product)
            ->setParameter('from', $from )
            ->setParameter('to', $to)
        ;
        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
