<?php

namespace TransactionBundle\Repository;

/**
 * STransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class STransactionRepository extends \Doctrine\ORM\EntityRepository
{
}
