<?php

namespace TransactionBundle\Repository;

/**
 * TransactionCostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionCostRepository extends \Doctrine\ORM\EntityRepository
{
}
