<?php

namespace KmBundle\Repository;

/**
 * ExpenditureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenditureRepository extends \Doctrine\ORM\EntityRepository
{
}
